version: "3"

services:

  #web:
  #  build:
  #    context: .
  #    dockerfile: ./Dockerfile-dev
  #  command: python manage.py runserver 0:8000
  #  ports:
  #    - "8000:8000"
  #  volumes:
  #    - .:/web
  #  depends_on:
  #    - db
  
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'chatu'
      MYSQL_USER: 'seungjae'
      MYSQL_PASSWORD: 'a123456789'
      MYSQL_ROOT_PASSWORD: 'a123456789'
    ports:
      - '3302:3302'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
